apiVersion: apps/v1
kind: Deployment
metadata:
  name: listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listener
  template:
    metadata:
      labels:
        app: listener
    spec:
      containers:
      - name: listener
        image: "bmigeri/listener:latest"
        env:
          - name: RABBIT_URL
            value: "amqp://guest:guest@rabbitmq"
        ports:
          - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: listener
spec:
  selector:
    app: listener
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80